[project]
name = "wpg-data-viz"
version = "0.1.0"
description = "Winnipeg Data Visualization dashboards"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.0",
    "ipykernel>=6.29.5",
    "pip>=25.0.1",
    "streamlit>=1.42.0",
]
